### ISSUE TITLE
Breaks front-end search

### ISSUE THREAD

**Issue by stompweb** [stuttter/wp-media-categories#1]
When activated, the plugin changes the post type of the front end search to 'attachment' which means posts aren't displayed in search results.

**Comment by JJJ** [comment]
Thanks @stompweb for the report.

I'll look into this and report back.

**Comment by JJJ** [comment]
Confirmed. Related to `wp_media_categories_pre_get_posts()`.

**Comment by JJJ** [comment]
This was a fun one. :)

**Comment by JJJ** [comment]
Fixed in 90ec7300593b24b0a99925de713df06b006c12e7.

**Comment by JJJ** [comment]
Related: https://core.trac.wordpress.org/ticket/37962
